### ISSUE TITLE
Missing dependency ncurses.h

### ISSUE THREAD

**Issue by xxmathias** [Scarlehh/Terminal-Bomberman#9]
When i run make:
```bash
[11:04] sata@DESKTOP-1O93UHD:~$ make
mkdir -p bin/
mkdir -p build/
gcc -c src/main.c -MMD -MF build/main.d -o build/main.o -lncursesw -pthread -g -I include/
src/main.c:3:10: fatal error: ncurses.h: No such file or directory
    3 | #include <ncurses.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [makefile:38: build/main.o] Error 1
```

i tried commenting this header file but it has lots of necessary code in it.

**Comment by dariota** [comment]
[ncurses](https://en.wikipedia.org/wiki/Ncurses) is a dependency of this repo which you should install separately, not by bundling it with the code. Based on your prompt, I suspect you're using WSL which runs on ubuntu, so you should be able to get this to build by running `sudo apt install ncurses-dev`.

By the way, this was a toy project for a hackathon a few years back - how did you run into this? 😄

**Comment by xxmathias** [comment]
I'm running WSL yes.
thank you very much, it is working now. I didn't know about ncurses.
A friend of mine asked me if there is a bomberman for the terminal, so i searched it on Google and came across this.
I'm thinking about working on it as a fun project. Powerups/Downgrades are still missing as posted in Issues

**Comment by dariota** [comment]
Sounds like fun! Feel free to fork the repo if you'd like to make your own changes directly, and if you'd like to send PRs back here I can have a look at them (no promises it'll be quick though!).

Gonna close this since it sounds like you're all good.
